# Generated by Django 5.2.1 on 2025-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField()),
                ('duracao_dias', models.IntegerField(default=30)),
                ('beneficios', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
