# Generated by Django 5.2.1 on 2025-05-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
            ],
            options={
                'unique_together': {('aluno', 'data')},
            },
        ),
    ]
