# Generated by Django 5.2.1 on 2025-05-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino'),
        ),
    ]
